language: node_js
node_js:
  - "0.12"
sudo: false

addons:
  code_climate:
    repo_token: 2dfacbf20f6196807d77967d4f8be4399057dbab3e6285362cdef1675dc1ba88

after_script:
  - codeclimate-test-reporter < coverage/lcov.info
